Repository BHoM/Versioning_Toolkit, pull requests merged in 2020-04, with the labels that each got.

#40 Removing any non-type part from the type string
  BHoMUpgrader/Upgrader.cs
Labels: type:bug

#38 Type Converter for ETABS PR281
  BHoMUpgrader31/TypeConverter.cs
Labels: type:feature

#67 Improve BHoM Upgrader handling of types
  BHoMUpgrader/Upgrader.cs
Labels: type:bug, type:feature
