Repository BHoM/Versioning_Toolkit, pull requests merged in 2020-12, with the labels that each got.

#108 Versioning for Space objects
  BHoMUpgrader40/Converter.cs
Labels: type:feature

#109 Align with changes to Structure_oM with removal of EmbodiedCarbon from MaterialFragments
  BHoMUpgrader40/Converter.cs
Labels: type:external-api-changes

#112 Fix typo in Converter
  BHoMUpgrader40/Converter.cs
Labels: type:bug

#114 Versioning added for FamilyLibrary
  BHoMUpgrader40/Converter.cs
Labels: type:bug

#118 Fix Upgrader for Space
  BHoMUpgrader/Upgrader.cs
  BHoMUpgrader40/Converter.cs
Labels: severity:critical, type:bug
