Repository BHoM/Versioning_Toolkit, pull requests merged in 2025-01, with the labels that each got.

#272 LadybugToolsToolkit versioning update
  BHoMUpgrader81/Converter.cs
Labels: type:feature

#274 Update version for PostBuild .exe
  PostBuild/Properties/AssemblyInfo.cs
Labels: type:bug

#278 RevitListenerAdapter removed from the test datasets
  .ci/code/Versioning_Test/Datasets/7.1/Adapters.json
  .ci/code/Versioning_Test/Datasets/7.2/Adapters.json
  .ci/code/Versioning_Test/Datasets/7.3/Adapters.json
  .ci/code/Versioning_Test/Datasets/8.0/Adapters.json
Labels: type:test-script
